//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharaChipGen.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharaChipGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleConfirm {
            get {
                return ResourceManager.GetString("DialogTitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleInformation {
            get {
                return ResourceManager.GetString("DialogTitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use parts setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemNameUsePartsSetting {
            get {
                return ResourceManager.GetString("ItemNameUsePartsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export successfully completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageExported {
            get {
                return ResourceManager.GetString("MessageExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Material directory not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageMaterialDirectoryNotFound {
            get {
                return ResourceManager.GetString("MessageMaterialDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accessory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameAccessories {
            get {
                return ResourceManager.GetString("NameAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Body に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameBodies {
            get {
                return ResourceManager.GetString("NameBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eye に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameEyes {
            get {
                return ResourceManager.GetString("NameEyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HairStyle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameHairStyles {
            get {
                return ResourceManager.GetString("NameHairStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HeadAccessory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameHeadAccessories {
            get {
                return ResourceManager.GetString("NameHeadAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Head に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameHeads {
            get {
                return ResourceManager.GetString("NameHeads", resourceCulture);
            }
        }
    }
}
